version: "3.3"
services:
	wordpress:
		image: debian:buster

		ports:

		depends_on:
			- nginx

	nginx:
		image: debian:buster

		ports:

	mariadb:
		image: debian:buster

		ports:

		depends_on:
			- nginx

volumes:
