version: "3.3"
services:
	wordpress:
		build: ./wordpress/.
		restart: always

		ports:

		volumes:

		depends_on:
			- nginx

	nginx:
		build: ./nginx/.
		restart: always

		ports:

	mariadb:
		build: ./mariadb/.
		restart: always

		ports:

		depends_on:
			- nginx
