version: "3.3"
services:
	wordpress:
		build: ./wordpress/.
		restart: always

		ports:

		volumes:
			- wp-files:/var/www

		depends_on:
			- nginx

	nginx:
		build: ./nginx/.
		restart: always

		volumes:
			- 

		ports:

	mariadb:
		build: ./mariadb/.
		restart: always

		ports:

		volumes:
			-
		depends_on:
			- nginx
networks:

volumes:
	wp_db:
		driver: local
		driver_opts:
			type: "none"
			o: "bind"
			device: /home/
	wp_files:
		driver: local
		driver_opts:
			type: "none"
			o: "bind"
			device: /home/sachouam/data/wp_files
