version: "3.3"
services:
  # wordpress:
  #   env_file:
  #     - .env
  #   build:
  #     context: ./wordpress/.
  #   image: wordpress:02
  #   restart: always
  #   container_name: wordpress
  #   volumes:
  #     - wp_files:/var/www/html
  #   depends_on:
  #     - mariadb
  # nginx:
  #   build:
  #     context: ./nginx/.
  #   env_file:
  #     - .env
  #   image: nginx:02
  #   restart: always
  #   container_name: nginx
  #   volumes:
  #     - wp_files:/var/www/html
  #   ports:
  #     - 443:443
  #   depends_on:
  #     - wordpress
  mariadb:
    env_file:
      - .env
    build:
      context: ./mariadb/.
    image: mariadb:02
    container_name: mariadb
    restart: always
    volumes:
      - wp_db:/var/www/html

networks:
  default:
    driver: custom-driver-1

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/wp_files