version: "3.3"
services:
# wordpress:
# 	build:
      context: ./wordpress/.
    image: wordpress:02
# 	restart: always

# 	expose:
# 		- 9000

# 	volumes:
# 		- wp_files:/var/www/html/wordpress

# 	depends_on:	
#     - mariadb
  nginx:
    build:
      context: ./nginx/.
    image: nginx:02
    restart: always
    container_name: nginx
    volumes:
      - wp_files:/var/www/html/wordpress
    ports:
      - 443:443
    depends_on:
      - wordpress
# mariadb:
# 	build:
      context: ./mariadb/.
    image: mariadb:02
# 	restart: always

# 	expose:
# 		- 3306
# 	volumes:
# 		- wp_db:/var/www/html
# 	environment:
# networks:

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/wp_files