version: "3.3"
services:
	wordpress:
		build: ./wordpress/.
		restart: always

		ports:

		volumes:
			- wp_files:/var/www/html

		depends_on:
			- nginx

	nginx:
		build: ./nginx/.
		restart: always

		volumes:
			- wp_files:/var/www/html

		ports:
			- 443:443

	mariadb:
		build: ./mariadb/.
		restart: always

		ports:
			- 3306:3306
		volumes:
			- wp_db:/var/www/html
		environment:
			
		depends_on:
			- nginx
networks:

volumes:
	wp_db:
		driver: local
		driver_opts:
			type: "none"
			o: "bind"
			device: ${HOME}/data/wp_db

	wp_files:
		driver: local
		driver_opts:
			type: "none"
			o: "bind"
			device: ${HOME}/data/wp_files
