version: "3.3"
services:
  wordpress:
    env_file:
      - .env
    build:
      context: ./wordpress/.
    image: wordpress:inception
    restart: always
    container_name: wordpress
    volumes:
      - wp_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
  nginx:
    build:
      context: ./nginx/.
    env_file:
      - .env
    image: nginx:inception
    restart: always
    container_name: nginx
    volumes:
      - wp_files:/var/www/html
    ports:
      - 443:443
      - 80:80
    depends_on:
      - wordpress
    networks:
      - inception
  mariadb:
    env_file:
      - .env
    build:
      context: ./mariadb/.
    image: mariadb:inception
    container_name: mariadb
    restart: always
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/wp_db
  wp_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${HOME}/data/wp_files